language: rust

install: sudo pip install ghp-import

script:
  - cargo doc
  - echo '<meta http-equiv=refresh content=0;url=Helion/index.html>' > target/doc/index.html
  - ghp-import -n target/doc
  - git push -qf https://$GH_TOKEN@github.com/bryal/Helion.git gh-pages

env:
    global:
      - secure: "ppeS5mGvppp3BVEZkn37kDVuiYhhYcxk/gonWYjYht34freD0EeKUXEXlMnjtwV1R+kvOVXvoZC/jSbMSpHwZ3zaTm3lMEjaIN+rQtc1b8LECcW9iN5mTp7kgu+IB5rGxynhmDPew4KXbnSjGhXpp9+GXg9HiWokQ/hzQ08pvS0="