[package]
name = "helion"
version = "0.1.3"
authors = ["bryal <96.bryal@gmail.com>"]
build = "build.rs"

[dependencies]
rustc-serialize = "*"
dxgcap = "*"
time = "*"

[dependencies.se_rs_ial]
git = "https://github.com/bryal/se-rs-ial"