[package]

name = "Helion"
version = "0.1.1"
authors = ["bryal <96.bryal@gmail.com>"]

build = "build.rs"

[dependencies]
rustc-serialize = "*"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.serial-rust]
git = "https://github.com/bryal/serial-rust"
# path = "../serial-rust"